document.writeln('<nav>');
document.writeln('    <div class=\'container\'>');
document.writeln('        <ul>');
document.writeln(
    '            <li><a href=\'./index.html\'>Hill⛰️</a></li>');
document.writeln('        </ul>');
document.writeln('        <ul>');
document.writeln('            <li><a href=\'./about.html\'>About</a></li>');
document.writeln('        </ul>');
document.writeln('        <ul>');
document.writeln('            <li><a href=\'./contact.html\'>Contact</a></li>');
document.writeln('        </ul>');
document.writeln('    </div>');
document.writeln('    <div class=\'under-nav\'>');
document.writeln('        <li><a href=\'./_blank.html\'>Sell product</a></li>');
document.writeln('        <li><a href=\'./_blank.html\'>Buy product</a></li>');
document.writeln('        <li><a href=\'./login.html\'>Login</a></li>');
document.writeln('        <li><a href=\'./signup.html\'>Sign up</a></li>');
document.writeln('    </div>');
document.writeln('</nav>');
document.writeln('<div class=\'header\'></div>');
document.writeln('<hr />');