document.writeln('<nav>');
document.writeln('    <div class=\'container\'>');
document.writeln('        <ul>');
document.writeln('            <li><a href="./index.html">Hill⛰️</a></li>');
document.writeln('        </ul>');
document.writeln('        <ul>');
document.writeln('            <li><a href=\'./about.html\'>About</a></li>');
document.writeln('        </ul>');
document.writeln('        <ul>');
document.writeln('            <li><a href=\'./contact.html\'>Contact</a></li>');
document.writeln('        </ul>');
document.writeln('    </div>');
document.writeln('</nav>');
document.writeln('<div class=\'header\'></div>');
document.writeln('<hr />');